### PR TITLE
(RHEL-30581) fix(github): update format of labeler

### PR DESCRIPTION
**Pull request by jamacku**
Since we are using `actions/labeler@main`, its format changed, displaying the following error with every new PR:

```
Run actions/labeler@main
The configuration file (path: .github/labeler.yml) was not found locally, fetching via the api
Error: Error: found unexpected type for label 'repository' (should be array of config options)
Error: found unexpected type for label 'repository' (should be array of config options)
```

(cherry picked from commit de8ac6300d115a05d467dbb6b9a7c2599a2d306f)

### CODE REVIEW

**Comment by pvalena** [comment]
Thanks! I was wondering why this issue was there ...

**Comment by jamacku** [comment]
It's because you are using `actions/labeler@main`, which is like using Fedora Rawhide. Every commit to the `main` branch can break your labeling workflow. If you were using `v4` in upstream instead, you would not be affected by breaking changes in `v5`: https://github.com/actions/labeler?tab=readme-ov-file#breaking-changes-in-v5

Overall it's not a good practice to use `main`|`master` branch. Use version or sha pinning instead:
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

@pvalena, this can happen again in the future.

**Comment by jamacku** [comment]
@pvalena, this PR should fix PR labeler and source-git automation (to check dracut issues instead of systemd and I have also updated the list of supported releases).

I'll waive CI, since all the changes will be taken into account only after they are merged.

**Comment by pvalena** [comment]
> @pvalena, this PR should fix PR labeler and source-git automation (to check dracut issues instead of systemd and I have also updated the list of supported releases).
> 
> I'll waive CI, since all the changes will be taken into account only after they are merged.

Right, LGTM, thanks a lot for looking into this!

**Pull request merged**
