### PR TITLE
feat(dmsquash-live): add new dmsquash-live-autooverlay module

### PR DESCRIPTION
**Pull request by Conan-Kudo**
Adapt to test properly with the CentOS Stream 9 container too.

<description/>

(cherry picked from commit a3c67d27e75223bb45df19f850d246ced9a09938)

Resolves: [#2135060](https://bugzilla.redhat.com/2135060)

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
cc: @iammattcoleman, @davide125, @michel-slm, @davdunc, @AdamWill, @cmurf

**Comment by pvalena** [comment]
Thanks for the PR!

**Comment by mrc0mmand** [comment]
I gave this a spin in #53 and after some tinkering and hunting down missing patches the test works even on C9S: https://github.com/redhat-plumbers/dracut-rhel9/actions/runs/3259533222/jobs/5352429481

@Conan-Kudo could you, please, cherry-pick dracutdevs/dracut@b8ffc87d13989f95c8f48ec64613dd9138835618 (there's a minor conflict in a comment) and add the TEST-16 to the C9S test list (e.g. https://github.com/redhat-plumbers/dracut-rhel9/pull/53/commits/f9e3fdb99a0e96d70e39d30ccb8d9cb87a6ab3b0)?

**Comment by Conan-Kudo** [comment]
@mrc0mmand Done!

**Pull request merged**
