### PR TITLE
(RHEL-27944) feat(systemd-pcrphase): introducing the systemd-pcrphase module

### PR DESCRIPTION
**Pull request by pvalena**
Introducing the systemd-pcrphase module

(Cherry-picked commit: c4c595ceeab79fefde74750ec6b0d15d7d16ede6)

Resolves: RHEL-27944

### CODE REVIEW

**Comment by pvalena** [comment]
LGTM.

**Comment by pvalena** [comment]
@jamacku btw. how do I add the upstream reference? :) we have `Cherry-picked commit: ....` there, but that's probably not enough.

**Comment by jamacku** [comment]
@pvalena, just use `git cherry-pick -x <sha>.` It will produce references in the correct form for you.

**Comment by pvalena** [comment]
Right, so it's just ` (cherry picked from commit ca5ae5d3466eec40d118fc96d450478aa6faebb6)`
instead of the original one... ok, thanks.

**Pull request merged**
