### PR TITLE
ci: use C9S chroots for Packit/TFT

### PR DESCRIPTION
**Pull request by mrc0mmand**

### CODE REVIEW

**Review by jamacku — COMMENTED** [review]
LGTM

**Comment by mrc0mmand** [comment]
C8S in TFT is currently borked, so let's wait a bit before merging this one.

**Comment by mrc0mmand** [comment]
Sweet, this should be finally ready to go (ignore the GH Actions fails for now).

@jamacku PTAL

**Review by jamacku — APPROVED** [review]
Looks good to me!

I'm only curious, why they are two checks  for the same thing (packit tests) in checks sections:

image

Isn't it created by default (in that case we could get rid of ``job: tests`` section)?

**Comment by mrc0mmand** [comment]
> Looks good to me!
> 
> I'm only curious, why they are two checks for the same thing (packit tests) in checks sections:
> 
> image
> 
> Isn't it created by default (in that case we could get rid of `job: tests` section)?

Interesting, it looks like one of the TF jobs were renamed, thus the duplication. Let me force-push the PR to see if it goes away.

**Comment by jamacku** [comment]
Yeah, that fixed the issue :+1:

**Pull request merged**
